# API Configuration
# Replace these with your actual API credentials
OPENAI_API_KEY = "sk-F8eR7EKmeVkfIERoA8D207A1100a4467Ad97609aA37e6fE7"
OPENAI_API_URL = "https://free.v36.cm/v1/chat/completions"
OPENAI_MODEL = "gpt-4o-mini"

# Optional Configuration
# Uncomment and modify if needed
# OPENAI_MAX_TOKENS = "1000"
# OPENAI_TEMPERATURE = "0.7"
# OPENAI_REQUEST_TIMEOUT = "30"
# CACHE_ENABLED = "True"
# CACHE_EXPIRY = "3600"
# MAX_RETRIES = "3" 